### ISSUE TITLE
need rebuild of package with GNU tar

### ISSUE THREAD

**Issue by qsimpleq** [kazuho/p5-Class-Accessor-Lite#8]
KAZUHO/Class-Accessor-Lite-0.07.tar.gz has a problem like [this]
(https://rt.cpan.org/Public/Bug/Display.html?id=86188) or [that](https://rt.cpan.org/Public/Bug/Display.html?id=98752)

**Comment by kazuho** [comment]
Oops!  Thank you for noticing the issue.  Shipped 0.08.
